### ISSUE TITLE
Fine-tune 

### ISSUE THREAD

**Issue by orchideous1** [Time-MoE/Time-MoE#17]
Thank you for sharing the code!!! I am wondering if I am to fine-tune the model on my own dataset. Should I construct my dataset strictly following the TimeMoEdataset code? 
After completing my dataset, is it sufficient to use the hf_trainer that has provided to perform lora fine-tune or should I implement something else?

**Comment by Maple728** [comment]
Thank you for your interest in our work.

You are correct. The time_moe_dataset is part of the training dataset; however, it needs to be encapsulated within a dataset that transforms a time series into multiple fixed-window-size time series, which can then be arranged into batch data. Afterward, you can use the hf_trainer to fine-tune the Time-MoE model. (I haven't tested LoRA fine-tuning on Time-MoE, so I'm uncertain if modifications are necessary for using LoRA. However, full fine-tuning should work without issues.)

We are currently preparing the code for fine-tuning forecasting, and it will be released in the coming week or two.

Please feel free to contact us if you have any other questions.

**Comment by orchideous1** [comment]
May I ask how to transforms a time series into multiple fixed-window-size time series so that the model can be trained?

**Comment by Maple728** [comment]
You can use a fixed-size sliding window to divide the original time series into multiple subsequences of the same size. These subsequences can then be organized into batches, which can be used to train the Time-MoE model.

Hope this helps you!

**Comment by Maple728** [comment]
The fine-tuning code is now available! You can find the tutorial in the `README.md`. I hope you find it helpful.

If you have any further questions, please don't hesitate to contact us.

**Comment by orchideous1** [comment]
Thanks for sharing your code !!! I found it greatly useful. However, There is still problems. When I switch the precision to fp16, errors occur.  
The message seem like these: 

Traceback (most recent call last):
  File "/data/tempuser/BigModel/Time-MoE/main.py", line 63, in <module>
    runner.train_model(
  File "/data/tempuser/BigModel/Time-MoE/time_moe/runner.py", line 180, in train_model
    trainer.train()
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/transformers/trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/transformers/trainer.py", line 3138, in training_step
    loss = self.compute_loss(model, inputs)
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/transformers/trainer.py", line 3161, in compute_loss
    outputs = model(**inputs)
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 186, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 201, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 108, in parallel_apply
    output.reraise()
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in _worker
    output = module(*input, **kwargs)
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/tempuser/BigModel/Time-MoE/time_moe/models/modeling_time_moe.py", line 997, in forward
    outputs = self.model(
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/tempuser/BigModel/Time-MoE/time_moe/models/modeling_time_moe.py", line 838, in forward
    inputs_embeds = self.embed_layer(input_ids)
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/tempuser/BigModel/Time-MoE/time_moe/models/modeling_time_moe.py", line 187, in forward
    emb = self.act_fn(self.gate_layer(x)) * self.emb_layer(x)
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/tempuser/anaconda3/envs/time-moe/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: float != c10::Half

**Comment by Maple728** [comment]
Thank you very much for pointing out the issue with training using fp16. This has been resolved in the latest main branch.

Please pull the latest branch and run the fine-tuning script. This should resolve the problem.

**Comment by orchideous1** [comment]
Thanks a lot!!!

**Comment by iganggang** [comment]
> Thank you for your interest in our work.
> 
> You are correct. The time_moe_dataset is part of the training dataset; however, it needs to be encapsulated within a dataset that transforms a time series into multiple fixed-window-size time series, which can then be arranged into batch data. Afterward, you can use the hf_trainer to fine-tune the Time-MoE model. (I haven't tested LoRA fine-tuning on Time-MoE, so I'm uncertain if modifications are necessary for using LoRA. However, full fine-tuning should work without issues.)
> 
> We are currently preparing the code for fine-tuning forecasting, and it will be released in the coming week or two.
> 
> Please feel free to contact us if you have any other questions.

Does the time-moe support the following fine-tuning methods: Full Fine-Tuning, Linear Probing, LoRA (Low-Rank Adaptation), and DoRA (Directional LoRA)?
