### ISSUE TITLE
TypeError: GenerationMixin._extract_past_from_model_output() got an unexpected keyword argument 'standardize_cache_format'

### ISSUE THREAD

**Issue by ldv1** [Time-MoE/Time-MoE#2]
Hi,

Thanks for releasing your code!

With the example you provide though, 

```
import torch
from transformers import AutoModelForCausalLM

context_length = 12
seqs = torch.randn(2, context_length)  # tensor shape is [batch_size, context_length]

model = AutoModelForCausalLM.from_pretrained(
    'Maple728/TimeMoE-50M',
    device_map="cpu",  # use "cpu" for CPU inference, and "cuda" for GPU inference.
    trust_remote_code=True,
)

# normalize seqs
mean, std = seqs.mean(dim=-1, keepdim=True), seqs.std(dim=-1, keepdim=True)
normed_seqs = (seqs - mean) / std

# forecast
prediction_length = 6
output = model.generate(normed_seqs, max_new_tokens=prediction_length)  # shape is [batch_size, 12 + 6]
normed_predictions = output[:, -prediction_length:]  # shape is [batch_size, 6]

# inverse normalize
predictions = normed_predictions * std + mean
```

an error is issued:

```
The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.
Traceback (most recent call last):
  File "/home/laurent/test/test.py", line 19, in <module>
    output = model.generate(normed_seqs, max_new_tokens=prediction_length)  # shape is [batch_size, 12 + 6]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/generation/utils.py", line 2048, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/generation/utils.py", line 3056, in _sample
    model_kwargs = self._update_model_kwargs_for_generation(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laurent/.cache/huggingface/modules/transformers_modules/Maple728/TimeMoE-50M/6bf56c13189f8ad41d9618f5e2d75f0b075f6590/ts_generation_mixin.py", line 206, in _update_model_kwargs_for_generation
    model_kwargs["past_key_values"] = self._extract_past_from_model_output(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GenerationMixin._extract_past_from_model_output() got an unexpected keyword argument 'standardize_cache_format'
```

I am using transformers version 4.45.1
Maybe it is related to transformers.

Thanks anyway for help.

**Comment by Maple728** [comment]
You are correct! Time-MoE requires transformers version 4.40.1. We modify the `_greedy_search` method of the class `GenerationMixin` to adopt the `generate` method of LLM, and it is only compatible with transformers version 4.40.1. 

We will attempt to adapt to the newer version of transformers in the future.

**Comment by ldv1** [comment]
Thanks for your prompt answer. I downgraded transformers to 4.40.1 and it worked.
